name: Build-Purple-Star
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build APK
        run: |
          chmod +x android/gradlew
          ./android/gradlew assembleDebug
      - name: Get APK
        uses: actions/upload-artifact@v3
        with:
          name: PurpleStar-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
